language: python
python:
  - "3.6"

cache:
  - pip
  - directories:
    ../sitetools

install:
  - pip install -r requirements.txt
  - pip install pytest

jobs:
  include:
    - stage: build
      script: ./.travis/install-sitetools.sh
    - stage: test
      script: ./.travis/create-test-config.sh && pytest
