version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST "sudo /var/www/collector/reload.sh"
      - run:
          name: Testing SSH
          command: ssh $SSH_USER@$SSH_HOST "touch /tmp/testfile"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master